export const PRODUCT_STATUSES = [
  { value: 'Draft', label: 'Draft' },
  { value: 'Published', label: 'Published' },
  { value: 'Unpublished', label: 'Unpublished' },
  { value: 'Archived', label: 'Archived' },
];

export const CATEGORIES = [
  { value: 'Sarees', label: 'Sarees' },
  { value: 'Lehengas', label: 'Lehengas' },
  { value: 'Salwar Suits', label: 'Salwar Suits' },
  { value: 'Kurtis', label: 'Kurtis' },
  { value: 'Gowns', label: 'Gowns' },
  { value: 'Accessories', label: 'Accessories' },
];

export const SUB_CATEGORIES = [
  { value: 'Silk Sarees', label: 'Silk Sarees' },
  { value: 'Cotton Sarees', label: 'Cotton Sarees' },
  { value: 'Georgette Sarees', label: 'Georgette Sarees' },
  { value: 'Chiffon Sarees', label: 'Chiffon Sarees' },
  { value: 'Linen Sarees', label: 'Linen Sarees' },
  { value: 'Banarasi Sarees', label: 'Banarasi Sarees' },
  { value: 'Kanjivaram Sarees', label: 'Kanjivaram Sarees' },
  { value: 'Organza Sarees', label: 'Organza Sarees' },
  { value: 'Net Sarees', label: 'Net Sarees' },
  { value: 'Tissue Sarees', label: 'Tissue Sarees' },
];

export const OCCASIONS = [
  { value: 'Wedding', label: 'Wedding' },
  { value: 'Festival', label: 'Festival' },
  { value: 'Party', label: 'Party' },
  { value: 'Casual', label: 'Casual' },
  { value: 'Office', label: 'Office' },
  { value: 'Daily Wear', label: 'Daily Wear' },
  { value: 'Engagement', label: 'Engagement' },
  { value: 'Reception', label: 'Reception' },
  { value: 'Haldi', label: 'Haldi' },
  { value: 'Mehendi', label: 'Mehendi' },
  { value: 'Sangeet', label: 'Sangeet' },
  { value: 'Diwali', label: 'Diwali' },
  { value: 'Pongal', label: 'Pongal' },
  { value: 'Onam', label: 'Onam' },
  { value: 'Puja', label: 'Puja' },
];

export const PRODUCT_TYPES = [
  { value: 'Silk', label: 'Silk' },
  { value: 'Cotton', label: 'Cotton' },
  { value: 'Georgette', label: 'Georgette' },
  { value: 'Chiffon', label: 'Chiffon' },
  { value: 'Linen', label: 'Linen' },
  { value: 'Banarasi', label: 'Banarasi' },
  { value: 'Kanjivaram', label: 'Kanjivaram' },
  { value: 'Organza', label: 'Organza' },
  { value: 'Net', label: 'Net' },
  { value: 'Tissue', label: 'Tissue' },
  { value: 'Handloom', label: 'Handloom' },
  { value: 'Tussar', label: 'Tussar' },
  { value: 'Patola', label: 'Patola' },
  { value: 'Bandhani', label: 'Bandhani' },
  { value: 'Lehenga', label: 'Lehenga' },
  { value: 'Salwar', label: 'Salwar' },
  { value: 'Kurti', label: 'Kurti' },
  { value: 'Gown', label: 'Gown' },
];

export const SAREES_FABRICS = [
  { value: 'Banarasi Silk', label: 'Banarasi Silk' },
  { value: 'Kanchipuram Silk', label: 'Kanchipuram Silk' },
  { value: 'Paithani Silk', label: 'Paithani Silk' },
  { value: 'Chanderi Silk', label: 'Chanderi Silk' },
  { value: 'Mysore Silk', label: 'Mysore Silk' },
  { value: 'Tussar Silk', label: 'Tussar Silk' },
  { value: 'Cotton Silk', label: 'Cotton Silk' },
  { value: 'Pure Cotton', label: 'Pure Cotton' },
  { value: 'Cotton Linen', label: 'Cotton Linen' },
  { value: 'Georgette', label: 'Georgette' },
  { value: 'Chiffon', label: 'Chiffon' },
  { value: 'Organza', label: 'Organza' },
  { value: 'Net', label: 'Net' },
  { value: 'Tissue', label: 'Tissue' },
  { value: 'Velvet', label: 'Velvet' },
  { value: 'Jacquard', label: 'Jacquard' },
  { value: 'Patola', label: 'Patola' },
  { value: 'Bandhani', label: 'Bandhani' },
  { value: 'Linen', label: 'Linen' },
  { value: 'Art Silk', label: 'Art Silk' },
];

export const BLOUSE_FABRICS = [
  { value: 'Silk', label: 'Silk' },
  { value: 'Cotton', label: 'Cotton' },
  { value: 'Georgette', label: 'Georgette' },
  { value: 'Chiffon', label: 'Chiffon' },
  { value: 'Satin', label: 'Satin' },
  { value: 'Velvet', label: 'Velvet' },
  { value: 'Net', label: 'Net' },
  { value: 'Organza', label: 'Organza' },
  { value: 'Brooch', label: 'Brooch' },
  { value: 'Same as Saree', label: 'Same as Saree' },
];

export const WORK_TYPES = [
  { value: 'Zari', label: 'Zari' },
  { value: 'Resham', label: 'Resham' },
  { value: 'Zardozi', label: 'Zardozi' },
  { value: 'Mirror Work', label: 'Mirror Work' },
  { value: 'Stone Work', label: 'Stone Work' },
  { value: 'Embroidery', label: 'Embroidery' },
  { value: 'Thread Work', label: 'Thread Work' },
  { value: 'Sequins', label: 'Sequins' },
  { value: 'Beads', label: 'Beads' },
  { value: 'Patch Work', label: 'Patch Work' },
  { value: 'Block Print', label: 'Block Print' },
  { value: 'Bandhani', label: 'Bandhani' },
  { value: 'Kalamkari', label: 'Kalamkari' },
  { value: 'Phulkari', label: 'Phulkari' },
  { value: 'Kashmiri', label: 'Kashmiri' },
  { value: 'Chikankari', label: 'Chikankari' },
  { value: 'Gota Patti', label: 'Gota Patti' },
  { value: 'Kundan', label: 'Kundan' },
  { value: 'Polki', label: 'Polki' },
  { value: 'Aari', label: 'Aari' },
];

export const BORDER_TYPES = [
  { value: 'Gold Border', label: 'Gold Border' },
  { value: 'Silver Border', label: 'Silver Border' },
  { value: 'Contrast Border', label: 'Contrast Border' },
  { value: 'Zari Border', label: 'Zari Border' },
  { value: 'Temple Border', label: 'Temple Border' },
  { value: 'Butti Border', label: 'Butti Border' },
  { value: 'Floral Border', label: 'Floral Border' },
  { value: 'Plain Border', label: 'Plain Border' },
  { value: 'Check Border', label: 'Check Border' },
  { value: 'Striped Border', label: 'Striped Border' },
  { value: 'Wide Border', label: 'Wide Border' },
  { value: 'Narrow Border', label: 'Narrow Border' },
  { value: 'Heavy Border', label: 'Heavy Border' },
  { value: 'Medium Border', label: 'Medium Border' },
  { value: 'No Border', label: 'No Border' },
];

export const PALLU_TYPES = [
  { value: 'Plain', label: 'Plain' },
  { value: 'Contrast', label: 'Contrast' },
  { value: 'Zari Work', label: 'Zari Work' },
  { value: 'Embroidered', label: 'Embroidered' },
  { value: 'Printed', label: 'Printed' },
  { value: 'Jacquard', label: 'Jacquard' },
  { value: 'Border Contrast', label: 'Border Contrast' },
  { value: 'Heavy Work', label: 'Heavy Work' },
  { value: 'Temple Design', label: 'Temple Design' },
  { value: 'Floral', label: 'Floral' },
];

export const PATTERNS = [
  { value: 'Solid', label: 'Solid' },
  { value: 'Printed', label: 'Printed' },
  { value: 'Woven', label: 'Woven' },
  { value: 'Embroidered', label: 'Embroidered' },
  { value: 'Striped', label: 'Striped' },
  { value: 'Checks', label: 'Checks' },
  { value: 'Floral', label: 'Floral' },
  { value: 'Geometric', label: 'Geometric' },
  { value: 'Abstract', label: 'Abstract' },
  { value: 'Paisley', label: 'Paisley' },
  { value: 'Butti', label: 'Butti' },
  { value: 'Jangla', label: 'Jangla' },
  { value: 'Temple', label: 'Temple' },
  { value: 'Ombre', label: 'Ombre' },
  { value: 'Dyed', label: 'Dyed' },
];

export const PRINT_TYPES = [
  { value: 'Block Print', label: 'Block Print' },
  { value: 'Digital Print', label: 'Digital Print' },
  { value: 'Screen Print', label: 'Screen Print' },
  { value: 'Hand Print', label: 'Hand Print' },
  { value: 'Discharge Print', label: 'Discharge Print' },
  { value: 'Rotary Print', label: 'Rotary Print' },
  { value: 'Transfer Print', label: 'Transfer Print' },
  { value: 'Heat Transfer', label: 'Heat Transfer' },
  { value: 'No Print', label: 'No Print' },
];

export const STYLES = [
  { value: 'Traditional', label: 'Traditional' },
  { value: 'Contemporary', label: 'Contemporary' },
  { value: 'Classic', label: 'Classic' },
  { value: 'Modern', label: 'Modern' },
  { value: 'Bohemian', label: 'Bohemian' },
  { value: 'Ethnic', label: 'Ethnic' },
  { value: 'Indo-Western', label: 'Indo-Western' },
  { value: 'Fusion', label: 'Fusion' },
  { value: 'Party Wear', label: 'Party Wear' },
  { value: 'Bridal', label: 'Bridal' },
  { value: 'Casual', label: 'Casual' },
  { value: 'Formal', label: 'Formal' },
];

export const COLORS = [
  { value: 'Red', label: 'Red', color: '#EF4444' },
  { value: 'Maroon', label: 'Maroon', color: '#800000' },
  { value: 'Pink', label: 'Pink', color: '#EC4899' },
  { value: 'Rose', label: 'Rose', color: '#F43F5E' },
  { value: 'Magenta', label: 'Magenta', color: '#D946EF' },
  { value: 'Purple', label: 'Purple', color: '#8B5CF6' },
  { value: 'Blue', label: 'Blue', color: '#3B82F6' },
  { value: 'Navy', label: 'Navy', color: '#1E3A5F' },
  { value: 'Teal', label: 'Teal', color: '#0D9488' },
  { value: 'Green', label: 'Green', color: '#22C55E' },
  { value: 'Emerald', label: 'Emerald', color: '#059669' },
  { value: 'Yellow', label: 'Yellow', color: '#EAB308' },
  { value: 'Gold', label: 'Gold', color: '#D4AF37' },
  { value: 'Orange', label: 'Orange', color: '#F97316' },
  { value: 'Peach', label: 'Peach', color: '#FFDAB9' },
  { value: 'Coral', label: 'Coral', color: '#FF7F50' },
  { value: 'Brown', label: 'Brown', color: '#8B4513' },
  { value: 'Beige', label: 'Beige', color: '#F5F5DC' },
  { value: 'Cream', label: 'Cream', color: '#FFFDD0' },
  { value: 'White', label: 'White', color: '#FFFFFF' },
  { value: 'Black', label: 'Black', color: '#000000' },
  { value: 'Grey', label: 'Grey', color: '#6B7280' },
  { value: 'Silver', label: 'Silver', color: '#C0C0C0' },
  { value: 'Multicolor', label: 'Multicolor', color: 'linear-gradient(90deg, red, orange, yellow, green, blue, purple)' },
];

export const BLOUSE_TYPES = [
  { value: 'Stitched', label: 'Stitched' },
  { value: 'Unstitched', label: 'Unstitched' },
  { value: 'Both', label: 'Both (Stitched & Unstitched)' },
  { value: 'Readymade', label: 'Readymade Blouse' },
  { value: 'Custom Stitched', label: 'Custom Stitched' },
];

export const GST_SLABS = [
  { value: '0', label: '0%' },
  { value: '5', label: '5%' },
  { value: '12', label: '12%' },
  { value: '18', label: '18%' },
  { value: '28', label: '28%' },
];

export const RETURN_DAYS_OPTIONS = [
  { value: '3', label: '3 Days' },
  { value: '7', label: '7 Days' },
  { value: '10', label: '10 Days' },
  { value: '15', label: '15 Days' },
  { value: '30', label: '30 Days' },
  { value: '45', label: '45 Days' },
  { value: '60', label: '60 Days' },
];